app:
  env: dev

logging:
  config: classpath:log4j2-dev.xml

spring:
  ## datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://host/open_mediation?useCursorFetch=true&characterEncoding=utf8&useSSL=true&requireSSL=false&allowLoadLocalInfile=true
    username: user
    password: pwd
  ## thymeleaf
  thymeleaf:
    cache: false # 开发时关闭缓存,不然没法看到实时页面

# currency api key from https://fixer.io
currency.api.appkey: REPLACE_YOUR_APPKEY