app:
  env: prod

logging:
  config: classpath:log4j2-prod.xml

spring:
  ## datasource
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://om.ckaigoijxdbf.rds.cn-north-1.amazonaws.com.cn:3306/open_mediation?useCursorFetch=true&characterEncoding=utf8&useSSL=false&allowLoadLocalInfile=true
    username: beijingssp
    password: beijingssp123

# currency api key from https://fixer.io
currency.api.appkey: your app key
